global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'application'
    scheme: http
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['spring-boot-prometheus-grafana:8080']